# Generated by Django 4.2.3 on 2023-07-18 22:28

import content.core.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('core', '0002_create_web_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='featured_image',
            field=wagtail.fields.StreamField([('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(required=False))], label='Image', template='patterns/blocks/image_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='website',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='website',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='website',
            name='story',
            field=wagtail.fields.StreamField([('text', wagtail.blocks.RichTextBlock(icon='pilcrow', template='patterns/blocks/text_block.html')), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(required=False)), ('alignment', content.core.blocks.ImageFormatChoiceBlock(default='full'))], label='Image', template='patterns/blocks/image_block.html')), ('image_grid', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('alt', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(required=False)), ('alignment', content.core.blocks.ImageFormatChoiceBlock(default='full'))])))], label='Image grid', template='patterns/blocks/image_grid_block.html')), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.RichTextBlock(form_classname='quote text')), ('attribution', wagtail.blocks.CharBlock(required=False)), ('attribution_url', wagtail.blocks.URLBlock(required=False))], template='patterns/blocks/blockquote_block.html')), ('pullquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(form_classname='quote title')), ('attribution', wagtail.blocks.CharBlock(required=False)), ('attribution_url', wagtail.blocks.URLBlock(required=False))], template='patterns/blocks/pullquote_block.html')), ('raw_html', wagtail.blocks.RawHTMLBlock(icon='code', label='Raw HTML', template='patterns/blocks/raw_html_block.html')), ('embed', wagtail.embeds.blocks.EmbedBlock(icon='code', template='patterns/blocks/embed_block.html')), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code', template='patterns/blocks/markdown_block.html'))], blank=True, use_json_field=True),
        ),
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_navigation', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Primary navigation', use_json_field=True)),
                ('footer_navigation', wagtail.fields.StreamField([('link', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=100)), ('link_page', wagtail.blocks.PageChooserBlock(required=False)), ('link_url', wagtail.blocks.URLBlock(required=False))]))], blank=True, help_text='Links at the bottom.', use_json_field=True)),
                ('footer_text', wagtail.fields.RichTextField(blank=True, help_text='Small print text at the bottom of all pages. Not required.')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
